### PR TITLE
feat: added config for environments

### PR DESCRIPTION
**Pull request by hekka**
[AB#294962](https://dev.azure.com/Equinor/62452b47-10ac-48f1-a5a1-803c0b9127ce/_workitems/edit/294962)

### CODE REVIEW

**Comment by davidramsay95** [comment]
@hekka these are just placeholders in all the fields, correct?

**Comment by hekka** [comment]
> @hekka these are just placeholders in all the fields, correct?

yes, key vaults and app regs are yet to be created, but made assumptions on kv urls

**Review by davidramsay95 — APPROVED** [review]
sweet

**Review by davidramsay95 — APPROVED** [review]
🐱

**Pull request merged**
